-[]Read Calculation of reduced density matrices from correlation functions by Peschel
-[]Continue rederiving calculations from Sipe paper
-[]Derive Eqn. 30 in Sipe paper, but without differentiating between inter and intra band contributions
